#!/bin/bash
# Autogenerated probe script for T4 validation
echo "=== Hostname ==="
hostname
echo "=== Kernel ==="
uname -a
echo "=== Docker Version ==="
docker --version
echo "=== Disk ==="
df -h /
echo "=== Memory ==="
free -h
